name: Deploy
run-name: Esmorga CMS deployment to ${{ inputs.environment }} 

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Deploy Environment
        required: true
        default: QA

  workflow_call:
    inputs:
      environment:
        description: Deploy Environment
        required: true
        type: string
        default: QA

env:
  BUILD_PACKAGE: build.zip
 
jobs:
  Deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create .env
      run: |
        echo "VITE_API_BASE_URL=${{vars.VITE_API_BASE_URL}}" >> .env 
        
    - name: Set up Python "pypy3.9"
      uses: actions/setup-python@v5
      with:
        python-version: pypy3.9

    - name: Build project
      run: |
        npm install
        npm run build
        cd ./dist
        zip -r $BUILD_PACKAGE ./*

    - name: Install dependencies And Deploy PROD
      shell: bash
      if: ${{ inputs.environment == 'PROD' }}
      run: |
        python -m pip install --upgrade pip paramiko 
        python .github/workflows/scripts/DeployToEnv.py $BUILD_PACKAGE cms.esmorgaevents.com ${{vars.SERVER_PATH}} ${{secrets.SERVER_CONNECTION_SSHRSA}}

    - name: Install dependencies And Deploy QA
      shell: bash
      if: ${{ inputs.environment == 'QA' }}
      run: |
        python -m pip install --upgrade pip paramiko 
        python .github/workflows/scripts/DeployToEnv.py $BUILD_PACKAGE qa.cms.esmorgaevents.com ${{vars.SERVER_PATH}} ${{secrets.SERVER_CONNECTION_SSHRSA}}

    - name: Remove .env
      run: |
        rm .env